@startuml

component app
component watchlist
component cmd

component api {
    component api.hello
    component api.movie
    component api.user
}

component extensions {
    component extensions.db
    component extensions.response
}

component dao {
    component dao.user
    component dao.movie
}

app --> watchlist : 创建 app


watchlist --> cmd : 注册
cmd --> extensions : 调用

watchlist --> extensions : 注册

watchlist --> api: 注册
api.hello --> extensions: 调用工具
api.user --> extensions: 调用工具
api.movie --> extensions: 调用工具

watchlist --> dao : 注册
dao.user --> extensions
dao.movie --> extensions


@enduml